# AI message: Responses generated by the model, including text content,tool calls, and metadata.
# 一个AIMessage代表模型调用的输出。它们可以包括多模态数据、工具调用以及您可以稍后访问的特定于提供者的元数据。
from langchain.messages import SystemMessage,HumanMessage,AIMessage
from langchain.chat_models import init_chat_model
from dotenv import load_dotenv  
import os
load_dotenv()
os.getenv("OPENAI_API_KEY")

model  = init_chat_model(
    model = "gpt-5.1",
    base_url = "http://localhost:8317/v1"
)

# response = model.invoke("Explain AI")
# print(type(response))  # <class 'langchain.messages.AIMessage'>

# 不同的提供者对消息类型的权衡/上下文化不同，
# 这意味着有时手动创建一个新的AIMessage对象并将其插入消息历史中，就好像它来自模型一样是有帮助的。
ai_msg = AIMessage("I'd be happy to help you with that question!")
# Add to conversation history
messages = [
    SystemMessage("You are a helpful assistant."),
    HumanMessage("Can you help me?"),
    ai_msg,
    HumanMessage("Great! What's 2+2?")
]

response = model.invoke(messages)

# AIMessage Attributes
print("text content:", response.text)  # Text content
print("content:", response.content)  # The raw content of the message
print("content_blocks:", response.content_blocks)  # The standardized content blocks of the message
print("tool calls:", response.tool_calls)  # Any tool calls made by the model
print("id:", response.id)  # A unique identifier for the message (either automatically generated by LangChain or returned in the provider response)
print("usage_metadata:", response.usage_metadata)  # The usage metadata of the message, which can contain token counts when available.
print("response_metadata:", response.response_metadata)  # The response metadata of the message

# Tool Calls
# def get_weather(location: str) -> str:
#     # Simulate a weather API call
#     return f"The weather in {location} is sunny with a high of 75°F."

# model_with_tools = model.bind_tools([get_weather])
# response = model_with_tools.invoke("What's the weather in Paris?")
# for tool_call in response.tool_calls:
#     print(f"Tool: {tool_call['name']}")
#     print(f"Args: {tool_call['args']}")
#     print(f"ID: {tool_call['id']}")
#     print(f"Type: {tool_call['type']}")